### ISSUE TITLE
打包时，报资源文件出错

### ISSUE THREAD

**Issue by w4mxl** [mjl0602/OVProgressHUD#13]
- 开发环境：
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (2 available)
```

- 错误信息：

```
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':ovprogresshud:verifyReleaseResources'.
[        ] > java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[        ]   /Users/wml/Development/workspace@Flutter/mobile_design_studio/build/ovprogresshud/intermediates/res/merged/release/values/values.xml:265: error:
resource android:attr/fontVariationSettings not found.
[        ]   /Users/wml/Development/workspace@Flutter/mobile_design_studio/build/ovprogresshud/intermediates/res/merged/release/values/values.xml:266: error:
resource android:attr/ttcIndex not found.
[        ]   error: failed linking references.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2m 31s
```

我搜索到其它一些插件也有[类似问题](https://github.com/hanxu317317/city_pickers/issues/75)，这个情况应该是升级 flutter 到 v1.12.13 版本后出现的。希望开发者能修复一下～

**Comment by wochen85** [comment]
我也遇到整个问题了，希望作者赶紧解决下

**Comment by 6ag** [comment]
这个项目应该放弃维护了，这个问题存在太久了

**Comment by w4mxl** [comment]
@wochen85 @6ag 我当时为了修复这个问题自己fork了一下这个库代码改的，如果需要可以在 yaml 用我这个 git（https://github.com/w4mxl/OVProgressHUD）

**Comment by PiN73** [comment]
> @wochen85 @6ag 我当时为了修复这个问题自己fork了一下这个库代码改的，如果需要可以在 yaml 用我这个 git（[https://github.com/w4mxl/OVProgressHUD）](https://github.com/w4mxl/OVProgressHUD%EF%BC%89)

@w4mxl thank you, it solves the problem! May you create a pull request to merge the fix into the package?

**Comment by w4mxl** [comment]
> > @wochen85 @6ag 我当时为了修复这个问题自己fork了一下这个库代码改的，如果需要可以在 yaml 用我这个 git（[https://github.com/w4mxl/OVProgressHUD）](https://github.com/w4mxl/OVProgressHUD%EF%BC%89)
> 
> @w4mxl thank you, it solves the problem! May you create a pull request to merge the fix into the package?

Sorry, I didn't submit a pull request because I was worried that the project was abandoned for maintenance.

**Comment by PiN73** [comment]
@mjl0602 would you merge this?

**Comment by mjl0602** [comment]
I suggest everyone use OKToast instead. @PiN73 @w4mxl @wochen85 

OKToast: https://github.com/OpenFlutter/flutter_oktoast
