### ISSUE TITLE
Bugs showSuccessWithStatus on next call

### ISSUE THREAD

**Issue by iambudi** [mjl0602/OVProgressHUD#4]
Calling Progresshud.show()/dismiss() works fine, but when calling showSuccess or Info or Error make the screen blocked since the progresshud does not dismiss for the second time it's called.

```
Progresshud.showSuccessWithStatus("Please wait...");
//Do something a bit long 2 - 3 seconds
await Progresshud.dismiss();
```

**Comment by mjl0602** [comment]
Did you miss "await" before "Progresshud.showSuccessWithStatus("Please wait...");"?
You must use await or .then here because it's async function.
