### ISSUE TITLE
About Progresshud.set***() in Android

### ISSUE THREAD

**Issue by w4mxl** [mjl0602/OVProgressHUD#9]
For example, when calling `Progresshud.setDefaultMaskTypeBlack(); ` . HUD should not appear, but it will appear on Android. **But there is no problem on iOS**.

Please check the problem. Thank you.

**Comment by usmanuj7** [comment]
@mjl0602  I am facing the same issue in `Progresshud.setDefaultMaskTypeGradient()` . In Android it show the Progress Hud but on iOS it works fine.

**Comment by mjl0602** [comment]
Fixed this bug on 0.2.4
